on:
  push:             
    branches: [ dev ]

jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Dependencies
          run: sudo apt-get install -y cmake g++ make
        - name: Build
          run: cd build && cmake .. && make
